site_name: Edy's Vehicle Physics
site_description: Documentation for Edy's Vehicle Physics (EVP), an easy to use vehicle physics package for Unity 3D
site_author: Angel "Edy" Garcia

strict: true
google_analytics: [ 'UA-58719504-2', 'auto' ]

theme:
    name: mkdocs
    custom_dir: 'custom_theme'

extra_css: [ 'css/tables.css', 'css/admonitions.css', 'css/fixes.css', 'css/extras.css', 'css/clickview.css' ]
extra_javascript: [ 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML', 'js/fabric.custom.min.js', 'js/texturecanvas.js', 'js/imagegallery.js', 'js/clickview.js' ]

markdown_extensions:
  - extra
  - admonition
  - codehilite
  - iconfonts:
      base: "fa"
      prefix: "fa-"
  - mdx_math:
      enable_dollar_delimiter: True

nav:
- "&#8201;": index.md
- User Guide:
  - Getting Started: user-guide/getting-started.md
  - Building scenes with vehicles: user-guide/building-scenes.md
  - Rigging vehicles: user-guide/rigging-vehicles.md
  - Markdown test page: test/markdown-test.md
- Components:
  - Vehicle: components/vehicle.md
  - Camera: components/camera.md
  - Ground Materials: components/ground-materials.md
  - Other: components/other.md
- FAQ / How To: faq.md
